---
# tasks file for pull_repository

- name: Pause for 2 minutes untill all packages have been loaded
  pause:
   minutes: 2

- name: Install git
  apt:
    name: git
    state: latest

- name: Pull repo
  git:
    repo: https://github.com/unicum0212/petclinic-java.git
    dest: "{{ home_dir }}"
    version: dev
